import { Footer } from "@/components/shared/footer";
import { Nav } from "@/components/shared/nav";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Poppins, Space_Grotesk, } from "next/font/google";
import "./globals.css";

const space = Space_Grotesk({ subsets: ["latin"], weight: ['400', '500', '600', '700'], variable: '--font-space' });

const poppins = Poppins({ subsets: ["latin"], weight: ['400', '500', '600'], variable: '--font-poppins' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('font-poppins overflow-x-hidden', space.variable, poppins.variable)}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
